# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_N01_V02.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_Paso01_LC_01_nx = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Paso01_LC_01_nx.setObjectName("lineEdit_Paso01_LC_01_nx")
        self.verticalLayout.addWidget(self.lineEdit_Paso01_LC_01_nx)
        self.lineEdit_Paso01_LC_02_x = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Paso01_LC_02_x.setObjectName("lineEdit_Paso01_LC_02_x")
        self.verticalLayout.addWidget(self.lineEdit_Paso01_LC_02_x)
        self.lineEdit_Paso01_LC_03_nt = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Paso01_LC_03_nt.setObjectName("lineEdit_Paso01_LC_03_nt")
        self.verticalLayout.addWidget(self.lineEdit_Paso01_LC_03_nt)
        self.lineEdit_Paso01_LC_04_dt = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Paso01_LC_04_dt.setObjectName("lineEdit_Paso01_LC_04_dt")
        self.verticalLayout.addWidget(self.lineEdit_Paso01_LC_04_dt)
        self.lineEdit_Paso01_LC_05_c = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Paso01_LC_05_c.setObjectName("lineEdit_Paso01_LC_05_c")
        self.verticalLayout.addWidget(self.lineEdit_Paso01_LC_05_c)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_Paso01_LC_06_u = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Paso01_LC_06_u.setObjectName("lineEdit_Paso01_LC_06_u")
        self.horizontalLayout.addWidget(self.lineEdit_Paso01_LC_06_u)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineEdit_Paso01_LC_07_x1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Paso01_LC_07_x1.setObjectName("lineEdit_Paso01_LC_07_x1")
        self.horizontalLayout_2.addWidget(self.lineEdit_Paso01_LC_07_x1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineEdit_Paso01_LC_08_x2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Paso01_LC_08_x2.setObjectName("lineEdit_Paso01_LC_08_x2")
        self.horizontalLayout_3.addWidget(self.lineEdit_Paso01_LC_08_x2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.pushButton_Paso01_LC_solver = QtWidgets.QPushButton(self.tab)
        self.pushButton_Paso01_LC_solver.setObjectName("pushButton_Paso01_LC_solver")
        self.verticalLayout_5.addWidget(self.pushButton_Paso01_LC_solver)
        self.progressBar_Paso01_LC_01 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_Paso01_LC_01.setProperty("value", 0)
        self.progressBar_Paso01_LC_01.setObjectName("progressBar_Paso01_LC_01")
        self.verticalLayout_5.addWidget(self.progressBar_Paso01_LC_01)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Paso01_LC_response_01 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Paso01_LC_response_01.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Paso01_LC_response_01.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.label_Paso01_LC_response_01.setText("")
        self.label_Paso01_LC_response_01.setObjectName("label_Paso01_LC_response_01")
        self.verticalLayout_4.addWidget(self.label_Paso01_LC_response_01)
        self.label_Paso01_LC_response_02 = QtWidgets.QLabel(self.groupBox_4)
        self.label_Paso01_LC_response_02.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.label_Paso01_LC_response_02.setText("")
        self.label_Paso01_LC_response_02.setObjectName("label_Paso01_LC_response_02")
        self.verticalLayout_4.addWidget(self.label_Paso01_LC_response_02)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_Paso01_NLC_01_nx = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Paso01_NLC_01_nx.setObjectName("lineEdit_Paso01_NLC_01_nx")
        self.verticalLayout_8.addWidget(self.lineEdit_Paso01_NLC_01_nx)
        self.lineEdit_Paso01_NLC_02_x = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Paso01_NLC_02_x.setObjectName("lineEdit_Paso01_NLC_02_x")
        self.verticalLayout_8.addWidget(self.lineEdit_Paso01_NLC_02_x)
        self.lineEdit_Paso01_NLC_03_nt = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Paso01_NLC_03_nt.setObjectName("lineEdit_Paso01_NLC_03_nt")
        self.verticalLayout_8.addWidget(self.lineEdit_Paso01_NLC_03_nt)
        self.lineEdit_Paso01_NLC_04_dt = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Paso01_NLC_04_dt.setObjectName("lineEdit_Paso01_NLC_04_dt")
        self.verticalLayout_8.addWidget(self.lineEdit_Paso01_NLC_04_dt)
        self.horizontalLayout_8.addLayout(self.verticalLayout_8)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.lineEdit_Paso01_NLC_06_ue = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_Paso01_NLC_06_ue.setObjectName("lineEdit_Paso01_NLC_06_ue")
        self.horizontalLayout_9.addWidget(self.lineEdit_Paso01_NLC_06_ue)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.lineEdit_Paso01_NLC_07_x1 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_Paso01_NLC_07_x1.setObjectName("lineEdit_Paso01_NLC_07_x1")
        self.horizontalLayout_11.addWidget(self.lineEdit_Paso01_NLC_07_x1)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.lineEdit_Paso01_NLC_08_x2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_Paso01_NLC_08_x2.setObjectName("lineEdit_Paso01_NLC_08_x2")
        self.horizontalLayout_12.addWidget(self.lineEdit_Paso01_NLC_08_x2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.gridLayout_9.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_7)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.pushButton_Paso01_NLC_solver = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Paso01_NLC_solver.setObjectName("pushButton_Paso01_NLC_solver")
        self.verticalLayout_6.addWidget(self.pushButton_Paso01_NLC_solver)
        self.progressBar_Paso01_NLC_01 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_Paso01_NLC_01.setProperty("value", 0)
        self.progressBar_Paso01_NLC_01.setObjectName("progressBar_Paso01_NLC_01")
        self.verticalLayout_6.addWidget(self.progressBar_Paso01_NLC_01)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_Paso01_NLC_response_01 = QtWidgets.QLabel(self.groupBox_8)
        self.label_Paso01_NLC_response_01.setMinimumSize(QtCore.QSize(100, 0))
        self.label_Paso01_NLC_response_01.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.label_Paso01_NLC_response_01.setText("")
        self.label_Paso01_NLC_response_01.setObjectName("label_Paso01_NLC_response_01")
        self.verticalLayout_10.addWidget(self.label_Paso01_NLC_response_01)
        self.label_Paso01_NLC_response_02 = QtWidgets.QLabel(self.groupBox_8)
        self.label_Paso01_NLC_response_02.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.label_Paso01_NLC_response_02.setText("")
        self.label_Paso01_NLC_response_02.setObjectName("label_Paso01_NLC_response_02")
        self.verticalLayout_10.addWidget(self.label_Paso01_NLC_response_02)
        self.gridLayout_10.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 22))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nasto"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Datos"))
        self.groupBox.setTitle(_translate("MainWindow", "Condiciones Iniciales"))
        self.label_1.setText(_translate("MainWindow", "nx ="))
        self.label_2.setText(_translate("MainWindow", "x ="))
        self.label_3.setText(_translate("MainWindow", "nt ="))
        self.label_4.setText(_translate("MainWindow", "dt ="))
        self.label_5.setText(_translate("MainWindow", "c ="))
        self.groupBox_2.setTitle(_translate("MainWindow", "Condiciones de borde"))
        self.label_6.setText(_translate("MainWindow", "u ="))
        self.label_7.setText(_translate("MainWindow", "x1 ="))
        self.label_8.setText(_translate("MainWindow", "x2 ="))
        self.pushButton_Paso01_LC_solver.setText(_translate("MainWindow", "Resolver y graficar"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Respuestas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "01. Ecuación lineal 1-D"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Datos"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Condiciones Iniciales"))
        self.label_9.setText(_translate("MainWindow", "nx ="))
        self.label_10.setText(_translate("MainWindow", "x ="))
        self.label_11.setText(_translate("MainWindow", "nt ="))
        self.label_12.setText(_translate("MainWindow", "dt ="))
        self.groupBox_7.setTitle(_translate("MainWindow", "Condiciones de borde"))
        self.label_14.setText(_translate("MainWindow", "u ="))
        self.label_15.setText(_translate("MainWindow", "x1 ="))
        self.label_16.setText(_translate("MainWindow", "x2 ="))
        self.pushButton_Paso01_NLC_solver.setText(_translate("MainWindow", "Resolver y graficar"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Respuestas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "02. Ecuación no lineal 1-D"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))

