# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIN01.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(547, 465)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line01nx = QtWidgets.QLineEdit(Dialog)
        self.line01nx.setObjectName("line01nx")
        self.verticalLayout.addWidget(self.line01nx)
        self.line02x = QtWidgets.QLineEdit(Dialog)
        self.line02x.setObjectName("line02x")
        self.verticalLayout.addWidget(self.line02x)
        self.line03nt = QtWidgets.QLineEdit(Dialog)
        self.line03nt.setObjectName("line03nt")
        self.verticalLayout.addWidget(self.line03nt)
        self.line04dt = QtWidgets.QLineEdit(Dialog)
        self.line04dt.setObjectName("line04dt")
        self.verticalLayout.addWidget(self.line04dt)
        self.line05c = QtWidgets.QLineEdit(Dialog)
        self.line05c.setObjectName("line05c")
        self.verticalLayout.addWidget(self.line05c)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.line06u = QtWidgets.QLineEdit(Dialog)
        self.line06u.setObjectName("line06u")
        self.horizontalLayout_4.addWidget(self.line06u)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.line07x1 = QtWidgets.QLineEdit(Dialog)
        self.line07x1.setObjectName("line07x1")
        self.horizontalLayout_2.addWidget(self.line07x1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.line08x2 = QtWidgets.QLineEdit(Dialog)
        self.line08x2.setObjectName("line08x2")
        self.horizontalLayout_3.addWidget(self.line08x2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.labelResponse01 = QtWidgets.QLabel(Dialog)
        self.labelResponse01.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.labelResponse01.setText("")
        self.labelResponse01.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResponse01.setObjectName("labelResponse01")
        self.verticalLayout_5.addWidget(self.labelResponse01)
        self.labelResponse02 = QtWidgets.QLabel(Dialog)
        self.labelResponse02.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.labelResponse02.setText("")
        self.labelResponse02.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResponse02.setObjectName("labelResponse02")
        self.verticalLayout_5.addWidget(self.labelResponse02)
        self.push02Graficar = QtWidgets.QPushButton(Dialog)
        self.push02Graficar.setObjectName("push02Graficar")
        self.verticalLayout_5.addWidget(self.push02Graficar)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Graficadora"))
        self.label.setText(_translate("Dialog", "ECUACIÓN DE CONVECCIÓN"))
        self.label_2.setText(_translate("Dialog", "nx ="))
        self.label_3.setText(_translate("Dialog", "x ="))
        self.label_4.setText(_translate("Dialog", "nt ="))
        self.label_5.setText(_translate("Dialog", "dt ="))
        self.label_6.setText(_translate("Dialog", "c ="))
        self.label_8.setText(_translate("Dialog", "Otros parámetros:"))
        self.label_7.setText(_translate("Dialog", "u ="))
        self.label_9.setText(_translate("Dialog", "x1 ="))
        self.label_10.setText(_translate("Dialog", "x2 ="))
        self.push02Graficar.setText(_translate("Dialog", "Resolver y Graficar"))

